app_root: .
ignored_folders:
  - vendor
  - log
  - logs
  - assets
  - public
  - grifts
  - tmp
  - bin
  - node_modules
  - .sass-cache
included_extensions:
  - .go
  - .env
build_path: ../../dist/buffalo
build_delay: 200ns
binary_name: libsrv-build
command_flags: []
enable_colors: true
log_name: libsrv
